### ISSUE TITLE
Gerar documentos PDF com python e elaborar páginas com Jinja para Flask

### ISSUE THREAD

**Issue by rrgaya** [filiperochalopes/mapa-upa-emergencia#1]
@filiperochalopes , pode me ajudar a entender alguns pontos? 

> Porém não pode ser algo que necessite de builds como Vue e React, mas sim Ready to use, por conta da especificidade de onde esse projeto será aplicado.

Referência: [Link](https://www.99freelas.com.br/project/gerar-documentos-pdf-com-python-e-elaborar-paginas-com-jinja-para-flask-373966?fs=t)

**Comment by filiperochalopes** [comment]
No caso digo a respeito de ser em uma estrutura de monolito com flask que tem estrutura para isso de forma organizada e não consumindo api de backend separado.
